---
- name: Testar módulo volume_snapshot sem criar snapshot
  hosts: localhost
  gather_facts: no
  collections:
    - openstack.cloud

  tasks:
    - name: Chamar volume_snapshot com state=absent em snapshot falso
      openstack.cloud.volume_snapshot:
        name: "dummy_snapshot_teste"
        volume: "dummy_volume_teste"
        state: absent
        cloud: "sua_cloud"  # Ajuste se você usa um nome de cloud em clouds.yaml
        wait: no
      register: test_result

    - name: Exibir resultado
      debug:
        var: test_result
