---
- name: Testar coleção openstack.cloud
  hosts: localhost
  gather_facts: no
  collections:
    - openstack.cloud

  tasks:
    - name: Invocar o módulo server_snapshot (teste)
      openstack.cloud.server_snapshot:
        name: "snapshot-teste"
        server: "fake-server"
        wait: no
      register: result

    - name: Mostrar resultado
      debug:
        var: result
