---
- name: Criar snapshot no OpenStack
  hosts: all
  gather_facts: false

  tasks:
    - name: Criar snapshot
      openstack.cloud.volume_snapshot:
        state: present
        name: "{{ snapshot_name }}"
        volume: "{{ snapshot_volume }}"
